[package]
name = "fonthelper"
version = "0.1.0"
authors = ["Chugunov Roman <Zebs-BMK@yandex.ru>"]
edition = "2018"
license = "GPL-2.0-only"
keywords = ["System", "Fonts"]

[dependencies]
finder = "0.1.1"
regex = "1.2.1"
freetype-rs = "0.20.0"
